# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from custom_components.ticktick_todo.pyticktick.openapi_client.models.project_data_response import ProjectDataResponse

class TestProjectDataResponse(unittest.TestCase):
    """ProjectDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectDataResponse:
        """Test ProjectDataResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectDataResponse`
        """
        model = ProjectDataResponse()
        if include_optional:
            return ProjectDataResponse(
                project = None,
                tasks = [
                    ''
                    ],
                columns = [
                    custom_components.ticktick_todo.pyticktick.openapi_client.models.column.Column(
                        id = '', 
                        project_id = '', 
                        name = '', 
                        sort_order = 56, )
                    ]
            )
        else:
            return ProjectDataResponse(
        )
        """

    def testProjectDataResponse(self):
        """Test ProjectDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
