# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from custom_components.ticktick_todo.pyticktick.openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_complete_specify_task(self) -> None:
        """Test case for complete_specify_task

        Complete a task by project ID and task ID  # noqa: E501
        """
        pass

    async def test_create_single_task(self) -> None:
        """Test case for create_single_task

        Create a task to TickTick  # noqa: E501
        """
        pass

    async def test_delete_specify_task(self) -> None:
        """Test case for delete_specify_task

        Delete a task by project ID and task ID  # noqa: E501
        """
        pass

    async def test_get_all_projects(self) -> None:
        """Test case for get_all_projects

        Get the list of projects  # noqa: E501
        """
        pass

    async def test_get_project_by_id(self) -> None:
        """Test case for get_project_by_id

        Get a project by ID  # noqa: E501
        """
        pass

    async def test_get_project_with_data_by_id(self) -> None:
        """Test case for get_project_with_data_by_id

        Get project with data by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
