# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from custom_components.ticktick_todo.pyticktick.openapi_client.models.task_response_all_of_status import TaskResponseAllOfStatus

class TestTaskResponseAllOfStatus(unittest.TestCase):
    """TaskResponseAllOfStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskResponseAllOfStatus:
        """Test TaskResponseAllOfStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskResponseAllOfStatus`
        """
        model = TaskResponseAllOfStatus()
        if include_optional:
            return TaskResponseAllOfStatus(
            )
        else:
            return TaskResponseAllOfStatus(
        )
        """

    def testTaskResponseAllOfStatus(self):
        """Test TaskResponseAllOfStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
