# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from custom_components.ticktick_todo.pyticktick.openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_oauth_token_post(self) -> None:
        """Test case for oauth_token_post

        Get token
        """
        pass

    def test_open_v1_project_get(self) -> None:
        """Test case for open_v1_project_get

        Get User Project.
        """
        pass

    def test_open_v1_project_post(self) -> None:
        """Test case for open_v1_project_post

        Create Project
        """
        pass

    def test_open_v1_project_project_id_data_get(self) -> None:
        """Test case for open_v1_project_project_id_data_get

        """
        pass

    def test_open_v1_project_project_id_delete(self) -> None:
        """Test case for open_v1_project_project_id_delete

        """
        pass

    def test_open_v1_project_project_id_get(self) -> None:
        """Test case for open_v1_project_project_id_get

        """
        pass

    def test_open_v1_project_project_id_post(self) -> None:
        """Test case for open_v1_project_project_id_post

        Update Project
        """
        pass

    def test_open_v1_project_project_id_task_task_id_complete_post(self) -> None:
        """Test case for open_v1_project_project_id_task_task_id_complete_post

        Update Task
        """
        pass

    def test_open_v1_project_project_id_task_task_id_delete(self) -> None:
        """Test case for open_v1_project_project_id_task_task_id_delete

        Delete task.
        """
        pass

    def test_open_v1_project_project_id_task_task_id_get(self) -> None:
        """Test case for open_v1_project_project_id_task_task_id_get

        Get Task By Project ID And Task ID.
        """
        pass

    def test_open_v1_task_post(self) -> None:
        """Test case for open_v1_task_post

        Create Task
        """
        pass

    def test_open_v1_task_task_id_post(self) -> None:
        """Test case for open_v1_task_task_id_post

        Update Task
        """
        pass


if __name__ == '__main__':
    unittest.main()
