# coding: utf-8

"""
    TickTick OpenAPI

    OpenAPI that allows the user to create and manage a TODO list using ChatGPT.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from custom_components.ticktick_todo.pyticktick.openapi_client.models.checklist_item import ChecklistItem  # noqa: E501

class TestChecklistItem(unittest.TestCase):
    """ChecklistItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChecklistItem:
        """Test ChecklistItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChecklistItem`
        """
        model = ChecklistItem()  # noqa: E501
        if include_optional:
            return ChecklistItem(
                id = '',
                title = '',
                status = 56,
                completed_time = '',
                is_all_day = '',
                sort_order = 56,
                start_date = '',
                time_zone = ''
            )
        else:
            return ChecklistItem(
        )
        """

    def testChecklistItem(self):
        """Test ChecklistItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
