openapi: 3.0.0
info:
  title: TickTick API
  description: [ TickTick ](https://ticktick.com/) TODO task manager.
  version: 0.0.1

servers:
  - url: https://api.ticktick.com
    description: Optional server description, e.g. Main (production) server

components:
  securitySchemes:
    BasicAuth:
      description: "client_id:client_secret"
      type: https
      scheme: basic
    BearerAuth:
      type: https
      scheme: bearer
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://ticktick.com/oauth/authorize
          tokenUrl: https://ticktick.com/oauth/token
          scopes:
            "tasks:write": ""
            "tasks:read": ""

  schemas:

    Status:
      description: Task completion status
      type: integer
      enum:
        - Normal
        -
        - Completed

    DateTime:
      example: "2019-11-13T03:00:00+0000"
      type: string
      format: date-time
      pattern: "yyyy-MM-dd'T'HH:mm:ssZ"

    TimeZone:
      example: "America/Los_Angeles"
      type: string

    ChecklistItem:
      type: object
      properties:
        id:
          description: Subtask identifier
          type: string
        title:
          description: Subtask title
          type: string
        status:
          allOf:
            - description: The completion status of subtask
            - $ref: "#/components/schemas/Status"
        completedTime:
          allOf:
            - description: Subtask completed time in "yyyy-MM-dd'T'HH:mm:ssZ"
            - $ref: "#/components/schemas/DateTime"
        isAllDay:
          description: All day
          type: boolean
        sortOrder:
          description: Subtask sort order
          example: 234444
          type: integer
        startDate:
          allOf:
            - description: Subtask start date time in "yyyy-MM-dd'T'HH:mm:ssZ"
            - $ref: "#/components/schemas/DateTime"
        timeZone:
          allOf:
            - description: Subtask timezone
            - $ref: "#/components/schemas/TimeZone"

    Task:
      type: object
      properties:
        title:
          description: Task title
          type: string
        isAllDay:
          description: All day
          type: boolean
        content:
          description: Task content
          type: string
        desc:
          description: Task description of checklist
          type: string
        dueDate:
          allOf:
            - description: Task due date time in "yyyy-MM-dd'T'HH:mm:ssZ"
            - $ref: "#/components/schemas/DateTime"
        items:
          description: Subtasks of Task
          type: array
          items:
            $ref: "#/components/schemas/ChecklistItem"
        priority:
          description: Task priority
          type: integer
          enum:
            - None
            - Low
            -
            - Medium
            -
            - High5
        reminders:
          description: List of reminder triggers
          example: [ "TRIGGER:P0DT9H0M0S", "TRIGGER:PT0S" ]
          type: array
          items:
            type: string
        repeatFlag:
          description: Recurring rules of task
          example: "RRULE:FREQ=DAILY;INTERVAL=1"
          type: string
        sortOrder:
          description: Task sort order
          example: 12345
          type: integer
        startDate:
          allOf:
            - description: Start date time in "yyyy-MM-dd'T'HH:mm:ssZ"
            - $ref: "#/components/schemas/DateTime"
        timeZone:
          allOf:
            - description: Task timezone
            - $ref: "#/components/schemas/TimeZone"

    TaskResponse:
      allOf:
        - $ref: "#/components/schemas/Task"
        - type: object
          properties:
            id:
              description: Task identifier
              type: string
            projectId:
              description: Task project id
              type: string
            completedTime:
              allOf:
                - description: Task completed time in "yyyy-MM-dd'T'HH:mm:ssZ"
                - $ref: "#/components/schemas/DateTime"
            status:
              allOf:
                - description: Task completion status
                - $ref: "#/components/schemas/Status"

    Project:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: name of the project
        color:
          description: color of project, eg. "#F18181"
          type: string
        sortOrder:
          description: sort order value of the project
          type: integer
        viewMode:
          description: view mode, "list", "kanban", "timeline"
          type: string
          enum:
            - list
            - kanban
            - timeline
        kind:
          description: project kind, "TASK", "NOTE"
          type: string
          enum:
            - TASK
            - NOTE
    ProjectResponse:
      allOf:
        - $ref: "#/components/schemas/Project"
        - type: object
          properties:
            id:
              type: string
              description: Project identifier
            closed:
              type: boolean
              description: Project closed
            groupId:
              type: string
              description: Project group identifier
            permission:
              type: string
              description: '"read", "write" or "comment"'

    Column:
      type: object
      properties:
        id:
          description: Column identifier
          type: string
        projectId:
          description: Project identifier
          type: string
        name:
          description: Column name
          type: string
        sortOrder:
          description: Order value
          type: integer

    ProjectData:
      type: object
      properties:
        project:
          allOf:
            - description: Project info
            - $ref: "#/components/schemas/ProjectResponse"
        tasks:
          description: Undone tasks under project
          type: array
          items:
            $ref: "#/components/schemas/TaskResponse"
        columns:
          description: Columns under project
          type: array
          items:
            $ref: "#/components/schemas/Column"
