openapi: 3.0.0
info:
  title: TickTick API task
  description: "[TickTick](https://ticktick.com/) TODO task manager."
  version: 0.0.1

paths:
  /open/v1/project/{projectId}/task/{taskId}:
    get:
      summary: Get Task By Project ID And Task ID.
      security:
        - OAuth2:
            - "tasks:read"
          BearerAuth: [ ]
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
          description:
            Project identifier
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description:
            Task identifier
      responses:
        "200": # status code
          description: OK
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/TaskResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found

    delete:
      summary: Delete task.
      security:
        - OAuth2:
            - "tasks:read"
          BearerAuth: [ ]
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
          description:
            Project identifier
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description:
            Task identifier
      responses:
        "200": # status code
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found

  /open/v1/task:
    post:
      summary: Create Task
      security:
        - OAuth2:
            - "tasks:read"
            - "tasks:write"
          BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/Task"
      responses:
        "200": # status code
          description: OK
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/TaskResponse"
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found


  /open/v1/task/{taskId}:
    post:
      summary: Update Task
      security:
        - OAuth2:
            - "tasks:read"
          BearerAuth: [ ]
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description:
            Task identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - properties:
                    taskId:
                      description: Task identifier
                      type: string
                - $ref: "schemas.yaml#/components/schemas/TaskResponse"
      responses:
        "200": # status code
          description: OK
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/TaskResponse"
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found

  /open/v1/project/{projectId}/task/{taskId}/complete:
    post:
      summary: Update Task
      security:
        - OAuth2:
            - "tasks:read"
          BearerAuth: [ ]
      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
          description:
            Project identifier
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description:
            Task identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                taskId:
                  type: string
      responses:
        "200": # status code
          description: OK
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
