# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictInt, StrictStr


class Column(BaseModel):
    """
    Column
    """
    id: Optional[StrictStr] = Field(default=None, description="Column identifier")
    project_id: Optional[StrictStr] = Field(default=None, alias="projectId", description="Project identifier")
    name: Optional[StrictStr] = Field(default=None, description="Column name")
    sort_order: Optional[StrictInt] = Field(default=None, alias="sortOrder", description="Order value")
    __properties = ["id", "projectId", "name", "sortOrder"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Column:
        """Create an instance of Column from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Column:
        """Create an instance of Column from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Column.parse_obj(obj)

        _obj = Column.parse_obj({
            "id": obj.get("id"),
            "project_id": obj.get("projectId"),
            "name": obj.get("name"),
            "sort_order": obj.get("sortOrder")
        })
        return _obj


