# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.task_response_all_of_completed_time import TaskResponseAllOfCompletedTime

class TestTaskResponseAllOfCompletedTime(unittest.TestCase):
    """TaskResponseAllOfCompletedTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskResponseAllOfCompletedTime:
        """Test TaskResponseAllOfCompletedTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskResponseAllOfCompletedTime`
        """
        model = TaskResponseAllOfCompletedTime()
        if include_optional:
            return TaskResponseAllOfCompletedTime(
            )
        else:
            return TaskResponseAllOfCompletedTime(
        )
        """

    def testTaskResponseAllOfCompletedTime(self):
        """Test TaskResponseAllOfCompletedTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
