# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.checklist_item import ChecklistItem

class TestChecklistItem(unittest.TestCase):
    """ChecklistItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChecklistItem:
        """Test ChecklistItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChecklistItem`
        """
        model = ChecklistItem()
        if include_optional:
            return ChecklistItem(
                id = '',
                title = '',
                status = None,
                completed_time = None,
                is_all_day = True,
                sort_order = 234444,
                start_date = None,
                time_zone = None
            )
        else:
            return ChecklistItem(
        )
        """

    def testChecklistItem(self):
        """Test ChecklistItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
